spring:
  application:
    name: eurka-server
server:
  port: 8761
#  servlet:
#    context-path: /rs

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    registerWithEureka: false   #\u662F\u5426\u5F00\u542F\u6CE8\u518C\u670D\u52A1\uFF0C\u56E0\u4E3A\u8FD9\u91CC\u5982\u679C\u4E3Atrue\u8868\u793A\u81EA\u5DF1\u6CE8\u518C\u81EA\u5DF1\uFF0C\u800C\u81EA\u5DF1\u5C31\u662F\u4E00\u4E2A\u670D\u52A1\u6CE8\u518C\u65B9\uFF0C\u6CA1\u5FC5\u8981\u81EA\u5DF1\u6CE8\u518C\u81EA\u5DF1
    fetchRegistry: false     #false\u8868\u793A\u81EA\u5DF1\u7AEF\u5C31\u662F\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u6211\u7684\u804C\u8D23\u5C31\u662F\u7EF4\u62A4\u670D\u52A1\u5B9E\u4F8B\uFF0C\u5E76\u4E0D\u9700\u8981\u53BB\u68C0\u7D22\u670D\u52A1
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 # \u81EA\u6211\u4FDD\u62A4\u6A21\u5F0F\u5173\u95ED
  server:
    enable-self-preservation: false


