
foo: footestString

server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/syllable2009/my-spring-cloud
#          uri: https://gitee.com/pengjunlee/config-cloud.git
          default-label: master
          search-paths: {application}
#          username: 你的码云账号
#          password: 你的账号密码
